#!/bin/sh
# Runs from /docker-entrypoint.d before nginx starts: make sure /certs holds
# a TLS setup for the :8443 listener. Two pieces, mkcert-style:
#
#   hydra-ca.crt/.key  a tiny local CA — THIS is what each controlling
#                      device imports as trusted (nginx serves it at
#                      /hydra.crt). Firefox/LibreWolf refuse Web MIDI on
#                      cert-override origins, and they also refuse a CA
#                      certificate presented as the server's own cert
#                      (MOZILLA_PKIX_ERROR_CA_CERT_USED_AS_END_ENTITY),
#                      so a single self-signed CA:TRUE cert cannot work.
#   hydra.crt/.key     the CA:FALSE server certificate (plus the CA
#                      appended as chain) that nginx actually serves.
#
# The CA survives SAN changes: only the server cert is re-issued, so
# devices that imported the CA once stay trusted when the rig gains a new
# name or IP. Mount /certs as a volume; drop your own hydra.crt/hydra.key
# there (a real or mkcert pair, no hydra.san marker) to use those instead.
set -e

# SANs only matter once a device trusts the CA (clicking through the
# warning ignores them) — list every name/IP the rig is reached by.
# Bare entries are auto-prefixed, so both spellings work:
#   HYDRA_TLS_SAN=DNS:localhost,IP:127.0.0.1,IP:192.168.88.100
#   HYDRA_TLS_SAN=localhost,127.0.0.1,192.168.88.100
raw="${HYDRA_TLS_SAN:-DNS:localhost,IP:127.0.0.1}"
san=""
for tok in $(echo "$raw" | tr ',' ' '); do
    case "$tok" in
        *:*) ;; # already prefixed (DNS:/IP:) — or IPv6, which needs IP: anyway
        *[!0-9.]*) tok="DNS:$tok" ;;
        *) tok="IP:$tok" ;;
    esac
    san="${san:+$san,}$tok"
done
marker="ca+leaf $san"

if [ -s /certs/hydra.crt ] && [ -s /certs/hydra.key ]; then
    # regenerate when the configured SAN (or the cert layout) changed since
    # WE generated the pair (marker file). A pair without marker is
    # user-provided — never touch — unless it carries our CN (generated by
    # an older image): adopt those with a one-time regeneration.
    if [ -f /certs/hydra.san ]; then
        [ "$(cat /certs/hydra.san)" = "$marker" ] && exit 0
        echo "hydra: TLS setup changed ($(cat /certs/hydra.san) -> $marker) — re-issuing server cert"
    else
        case "$(openssl x509 -in /certs/hydra.crt -noout -subject 2>/dev/null)" in
            *hydra-lan*) echo "hydra: upgrading pre-existing self-signed cert to CA + server pair (SAN $san)" ;;
            *) exit 0 ;;
        esac
    fi
    rm -f /certs/hydra.crt /certs/hydra.key
fi

# the CA is created once and then reused, so re-issuing the server cert
# (new SAN) never invalidates the trust a device already granted
if [ ! -s /certs/hydra-ca.crt ] || [ ! -s /certs/hydra-ca.key ]; then
    openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
        -keyout /certs/hydra-ca.key -out /certs/hydra-ca.crt \
        -subj "/CN=hydra-lan CA" \
        -addext "basicConstraints=critical,CA:TRUE" \
        -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null
    echo "hydra: generated local CA (import /hydra.crt on each controlling device)"
fi

ext="/tmp/hydra-leaf.ext.$$"
cat > "$ext" <<EOF
subjectAltName=$san
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth
EOF
openssl req -newkey rsa:2048 -nodes -keyout /certs/hydra.key \
    -out "/tmp/hydra-leaf.csr.$$" -subj "/CN=hydra-lan" 2>/dev/null
openssl x509 -req -in "/tmp/hydra-leaf.csr.$$" -sha256 -days 3650 \
    -CA /certs/hydra-ca.crt -CAkey /certs/hydra-ca.key -CAcreateserial \
    -extfile "$ext" -out /certs/hydra.crt 2>/dev/null
# serve the full chain so every client can build the path to the CA
cat /certs/hydra-ca.crt >> /certs/hydra.crt
rm -f "$ext" "/tmp/hydra-leaf.csr.$$"
printf '%s' "$marker" > /certs/hydra.san
echo "hydra: issued server TLS cert (SAN $san) signed by the local CA"
