#!/bin/sh
# Runs from /docker-entrypoint.d before nginx starts: make sure /certs holds
# a TLS keypair for the :8443 listener. Self-signed is the point — on a LAN
# rig each controlling device accepts the browser warning once, and the deck
# becomes a secure context (Web MIDI, mic, wake lock). Mount /certs as a
# volume so the cert (and the accepted exceptions) survive recreates; drop
# your own hydra.crt/hydra.key there to use a real or mkcert-issued pair.
set -e
# SANs only matter once a device IMPORTS the cert as trusted (clicking
# through the warning ignores them) — so list every name/IP the rig is
# reached by. Bare entries are auto-prefixed, so both spellings work:
#   HYDRA_TLS_SAN=DNS:localhost,IP:127.0.0.1,IP:192.168.88.100
#   HYDRA_TLS_SAN=localhost,127.0.0.1,192.168.88.100
raw="${HYDRA_TLS_SAN:-DNS:localhost,IP:127.0.0.1}"
san=""
for tok in $(echo "$raw" | tr ',' ' '); do
    case "$tok" in
        *:*) ;; # already prefixed (DNS:/IP:) — or IPv6, which needs IP: anyway
        *[!0-9.]*) tok="DNS:$tok" ;;
        *) tok="IP:$tok" ;;
    esac
    san="${san:+$san,}$tok"
done
if [ -s /certs/hydra.crt ] && [ -s /certs/hydra.key ]; then
    # regenerate when the configured SAN changed since WE generated the pair
    # (marker file). A pair without marker is user-provided — never touch —
    # unless it carries our CN (generated by an older image, before the
    # marker existed): adopt those with a one-time regeneration, which also
    # upgrades them to CA:TRUE for the trusted-import flow.
    if [ -f /certs/hydra.san ]; then
        [ "$(cat /certs/hydra.san)" = "$san" ] && exit 0
        echo "hydra: TLS SAN changed ($(cat /certs/hydra.san) -> $san) — regenerating cert"
    else
        case "$(openssl x509 -in /certs/hydra.crt -noout -subject 2>/dev/null)" in
            *hydra-lan*) echo "hydra: upgrading pre-existing self-signed cert (SAN $san, CA:TRUE)" ;;
            *) exit 0 ;;
        esac
    fi
    rm -f /certs/hydra.crt /certs/hydra.key
fi
# CA:TRUE lets Firefox/LibreWolf/Android import the cert into their
# authority store, turning :8443 into a fully valid origin — which is what
# Firefox-family browsers require before they grant Web MIDI (they deny it
# silently on cert-override origins). nginx serves the public half at
# /hydra.crt for exactly that import.
openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
    -keyout /certs/hydra.key -out /certs/hydra.crt \
    -subj "/CN=hydra-lan" -addext "subjectAltName=$san" \
    -addext "basicConstraints=critical,CA:TRUE" 2>/dev/null
printf '%s' "$san" > /certs/hydra.san
echo "hydra: generated self-signed TLS cert (SAN $san) in /certs"
